Adobe_ProjectX/urls.py
from django.contrib import admin
from django.urls import path, include
from flagstone import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', include('flagstone.urls'), name='index'),
    path('admin/', admin.site.urls),
    path('flagstone/', include('flagstone.urls'), name='flagstone'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('accounts/', include('django.contrib.auth.urls')), # new
    
]

urlpatterns += staticfiles_urlpatterns()

flagstone/urls.py
from django.urls import path
from flagstone import views

app_name = 'flagstone'

urlpatterns = [
	# path('index_list/', views.IndexListView.as_view(), name='index_list'),
	path('customer_list/', views.CustomerListView.as_view(), name='customer_list'),
	path('customer_list/<int:pk>', views.CustomerDetailView.as_view(), name='customer_detail'),
	path('create_customer/', views.CustomerCreateView.as_view(), name='create_customer'),
	path('update_customer/<int:pk>', views.CustomerUpdateView.as_view(), name='update_customer'),
	path('delete_customer/<int:pk>', views.CustomerDeleteView.as_view(), name='delete_customer'),

	path('', views.IndexListView.as_view(), name='home'),
	path('rental_statement/<int:pk>', views.RentalDetailView.as_view(), name='rental_statement'),
	path('rental_list/', views.RentalListView.as_view(), name='rental_list'),
	path('rental_list/<int:pk>', views.RentalDetailView.as_view(), name='rental_detail'),
	path('rental_detail/<int:pk>', views.RentalDetailView.as_view(), name='rental_detail_pdf'),
	path('create_rental/', views.RentalCreateView.as_view(), name='create_rental'),
	path('update_rental/<int:pk>', views.RentalUpdateView.as_view(), name='update_rental'),
	path('delete_rental/<int:pk>', views.RentalDeleteView.as_view(), name='delete_rental'),


	path('shuttle_list/', views.ShuttleListView.as_view(), name='shuttle_list' ),
	path('shuttle_statememt/<int:pk>', views.ShuttleDetailView.as_view(), name='shuttle_statement'),
	path('shuttle_list/<int:pk>', views.ShuttleDetailView.as_view(), name='shuttle_detail' ),
	path('shuttle_create/', views.ShuttleCreateView.as_view(), name='shuttle_create' ),
	path('shuttle_update/<int:pk>', views.ShuttleUpdateView.as_view(), name='shuttle_update' ),
	path('shuttle_delete/<int:pk>', views.ShuttleDeleteView.as_view(), name='shuttle_delete' ),


	path('praasa_list/', views.PRAASA_March2020ListView.as_view(), name='praasa_list' ),
	path('praasa_statememt/<int:pk>', views.PRAASA_March2020DetailView.as_view(), name='praasa_statement'),
	path('praasa_list/<int:pk>', views.PRAASA_March2020DetailView.as_view(), name='praasa_detail' ),
	path('praasa_create/', views.PRAASA_March2020CreateView.as_view(), name='praasa_create' ),
	path('praasa_update/<int:pk>', views.PRAASA_March2020UpdateView.as_view(), name='update_praasa' ),
	path('praasa_delete/<int:pk>', views.PRAASA_March2020DeleteView.as_view(), name='praasa_delete' ),

	path('carf_list/', views.CustomerCARFListView.as_view(), name='carf_list' ),
	path('carf_statememt/<int:pk>', views.CustomerCARFDetailView.as_view(), name='carf_statement'),
	path('carf_list/<int:pk>', views.CustomerCARFDetailView.as_view(), name='carf_detail' ),
	path('carf_form/', views.CustomerCARFCreateView.as_view(), name='carf_form' ),
	path('carf_update/<int:pk>', views.CustomerCARFUpdateView.as_view(), name='carf_update' ),
	# path('carf_delete/<int:pk>', views.CustomerCARFDeleteView.as_view(), name='carf_delete' ),



	path('van_list/', views.VanListView.as_view(), name='van_list'),
	path('van_list/<int:pk>', views.VanDetailView.as_view(), name='van_detail'),
	path('create_van/', views.VanCreateView.as_view(), name='create_van'),
	path('update_van/<int:pk>', views.VanUpdateView.as_view(), name='update_van'),
	path('delete_van/<int:pk>', views.VanDeleteView.as_view(), name='delete_van'),

	path('pdf/<int:pk>', views.GeneratePDF.as_view(), name='pdf'),

	path('tables/', views.tables, name='tables'),
	path('register/', views.register, name='register'),
	path('user_login/', views.user_login,name='user_login'),
	path('some_view/', views.some_view, name='some_view'),

	path('organization_list/', views.OrganizationListView.as_view(), name='organization_list'),
	path('organization_detail/<int:pk>', views.OrganizationDetailView.as_view(), name='organization_detail'),
	path('organization_create/', views.OrganizationCreateView.as_view(), name='organization_create'),
	path('organization_update/<int:pk>', views.OrganizationUpdateView.as_view(), name='organization_update'),
	path('organization_delete/<int:pk>', views.OrganizationDeleteView.as_view(), name='organization_delete'),


	path('driver_list/', views.AdobeDriverListView.as_view(), name='adobedriver_list'),
	path('driver_list/<int:pk>', views.AdobeDriverDetailView.as_view(), name='adobedriver_detail'),
	path('driver_detail/<int:pk>', views.AdobeDriverDetailView.as_view(), name='adobedriver_detail'),

	path('driver_create/', views.AdobeDriverCreateView.as_view(), name='adobedriver_create'),

	path('driver_update/<int:pk>', views.AdobeDriverUpdateView.as_view(), name='adobedriver_update'),
	path('driver_delete/<int:pk>', views.AdobeDriverDeleteView.as_view(), name='adobedriver_delete'),


	path('vanmaintenancelog_list/', views.VanMaintenanceLogListView.as_view(), name='vanmaintenancelog_list'),
	path('vanmaintenancelog_list/<int:pk>', views.VanMaintenanceLogDetailView.as_view(), name='vanmaintenancelog_detail'),
	path('vanmaintenancelog_create/', views.VanMaintenanceLogCreateView.as_view(), name='vanmaintenancelog_create'),
	path('vanmaintenancelog_update/<int:pk>', views.VanMaintenanceLogUpdateView.as_view(), name='vanmaintenancelog_update'),
	path('vanmaintenancelog_delete/<int:pk>', views.VanMaintenanceLogDeleteView.as_view(), name='vanmaintenancelog_delete'),

	path('vaninspectionlog_list/', views.VanInspectionLogListView.as_view(), name='vaninspectionlog_list'),
	path('vaninspectionlog_list/<int:pk>', views.VanInspectionLogDetailView.as_view(), name='vaninspectionlog_detail'),
	path('vaninspectionlog_create/', views.VanInspectionLogCreateView.as_view(), name='vaninspectionlog_create'),
	path('vaninspectionlog_update/<int:pk>', views.VanInspectionLogUpdateView.as_view(), name='vaninspectionlog_update'),
	path('vaninspectionlog_delete/<int:pk>', views.VanInspectionLogDeleteView.as_view(), name='vaninspectionlog_delete'),

	path('timesheet_list/', views.TimeSheetListView.as_view(), name='timesheet_list'),
	path('timesheet_list/<int:pk>', views.TimeSheetDetailView.as_view(), name='timesheet_detail'),
	path('timesheet_create/', views.TimeSheetCreateView.as_view(), name='timesheet_create'),
	path('timesheet_update/<int:pk>', views.TimeSheetUpdateView.as_view(), name='timesheet_update'),
	path('timesheet_delete/<int:pk>', views.TimeSheetDeleteView.as_view(), name='timesheet_delete'),

	path('driverassignment_list/', views.DriverAssignmentListView.as_view(), name='driverassignment_list'),
	path('driverassignment_list/<int:pk>', views.DriverAssignmentDetailView.as_view(), name='driverassignment_detail'),
	path('driverassignment_create/', views.DriverAssignmentCreateView.as_view(), name='driverassignment_create'),
	path('driverassignment_update/<int:pk>', views.DriverAssignmentUpdateView.as_view(), name='driverassignment_update'),
	path('driverassignment_delete/<int:pk>', views.DriverAssignmentDeleteView.as_view(), name='driverassignment_delete'),

	
	# path('driverreview_list/', views.DriverReviewListView.as_view(), name='driverreview_list'),
	# path('driverreview_list/<int:pk>', views.DriverReviewDetailView.as_view(), name='driverreview_detail'),
	# path('driverreview_create/', views.DriverReviewCreateView.as_view(), name='driverreview_create'),
	# path('driverreview_update/<int:pk>', views.DriverReviewUpdateView.as_view(), name='driverreview_update'),
	# path('driverreview_delete/<int:pk>', views.DriverReviewDeleteView.as_view(), name='driverreview_delete'),


]



'''
Organization_Affiliate
Event
ShuttleService
AirportShuttleService
SpecialShuttle
SpecialEvent
DriverReview
'''

flagstone/forms.py
from django import forms
from django.contrib.auth.models import User

from flagstone.models import UserProfileInfo, Rental

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site', 'profile_pic')

# class RentalForm(forms.ModelForm):
# 	class Meta():
# 		model = Rental 
# 		rental_date = DateTimeField()

class DateWidgetForm(forms.DateInput):
	input_type = 'date'

class TimeWidgetForm(forms.DateTimeInput):
	input_type = 'time'

class NewRentalForm(forms.ModelForm):
	class Meta():
		model = Rental 
		fields = [
			'status_type', 
			'customer', 
			'van_number', 
			'rental_date', 
			'return_date', 
			'daily_rate', 
			'additional_driver_rate', 
			'mexico_insurance_rate', 
			'roadside_assistance_rate', 
			'us_insurance_rate', 
			'hitch_rate', 
			'luggage_rack_rate', 
			'daily_allowed_miles', 
			'mileage_over_rate', 
			'drop_fee', 
			'lic_tax', 
			'sales_tax', 
			'surcharge', 
			'airport_access_fee', 
			'airport_pickup_fee', 
			'drop_fee', 
			'misc_fee', 
			'misc_fee_text', 
			'date_returned', 
			'odometer_in', 
			'odometer_out', 
			'total_due_status', 
			'final_total_status',
		]

		widgets = {
			'rental_date': DateWidgetForm(),
			'return_date': TimeWidgetForm()
		}

	# ## additional driver add on ## ForeignKey model was throwing errors
	# lic_class = (('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D-Operator'))
	# damage_type = (('0', 'Undamaged'), ('1', 'Damaged'), ('2', 'Preexisting Damage') )

# customer
# rental_date
# return_date
# van_rented
# status_type
# daily_rate
# allowed_daily_miles
# mileage_over_rate
# additional_driver_fee
# mexico_insurance
# roadside_assistance
# additional_driver_01_first_name
# additional_driver_01_last_name
# additional_driver_01_phone
# additional_driver_01_email
# additional_driver_01_z_code
# additional_driver_01_d_lic_num
# additional_driver_01_d_lic_class
# additional_driver_01_d_lic_exp
# additional_driver_01_d_dob
# additional_driver_02_first_name
# additional_driver_02_last_name
# additional_driver_02_phone
# additional_driver_02_email
# additional_driver_02_z_code
# additional_driver_02_d_lic_num
# additional_driver_02_d_lic_class
# additional_driver_02_d_lic_exp
# additional_driver_02_d_dob
# surcharge
# lic_tax
# city_sales_tax
# airport_access_fee
# drop_fee
# date_returned
# late_charge
# miles_over_fee
# cleaning_fee
# other_fee
# fuel_charge
# notes
# gas_out
# odometer_out
# van_out_text
# odometer_in
# gas_in
# van_in_text
# windshield_out
# grill_out
# front_bumper_out
# rear_bumper_out
# backdoor_out
# backdoor_widow_out
# seats_out
# carpet_out
# driver_side_seat_out
# driver_side_front_tire_out
# driver_side_rear_tire_out
# driver_side_window_out
# driver_side_rear_window_out
# driver_side_mid_window_out
# driver_side_front_quarter_panel_out
# driver_side_mid_panel_out
# driver_side_rear_quarter_panel_out
# pass_side_seat_out
# pass_side_front_tire_out
# pass_side_rear_tire_out
# pass_side_window_out
# pass_side_rear_window_out
# pass_side_mid_window_out
# pass_side_front_quarter_panel_out
# pass_side_mid_panel_out
# pass_side_rear_quarter_panel_out
# windshield_retrun
# grill_retrun
# front_bumper_retrun
# rear_bumper_retrun
# backdoor_retrun
# backdoor_widow_retrun
# seats_retrun
# carpet_retrun
# driver_side_seat_retrun
# driver_side_front_tire_retrun
# driver_side_rear_tire_retrun
# driver_side_window_retrun
# driver_side_rear_window_retrun
# driver_side_mid_window_retrun
# driver_side_front_quarter_panel_retrun
# driver_side_mid_panel_retrun
# driver_side_rear_quarter_panel_retrun
# pass_side_seat_retrun
# pass_side_front_tire_retrun
# pass_side_rear_tire_retrun
# pass_side_window_retrun
# pass_side_rear_window_retrun
# pass_side_mid_window_retrun
# pass_side_front_quarter_panel_retrun
# pass_side_mid_panel_retrun
# pass_side_rear_quarter_panel_retrun

flagstone/templates/flagstone/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<title>Adobe Transportation</title>
	    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav-one">
  <a class="navbar-brand" href="{% url 'flagstone:home' %}"><img src="{% static 'media/solo.png' %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rentals
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          
           
          <a class="dropdown-item" href="{% url 'flagstone:create_rental' %}">New Rental</a>    
          <!-- <a class="dropdown-item" href="#">New Shuttle</a>  -->
         <a class="dropdown-item" href="{% url 'flagstone:rental_list' %}">Rentals</a> 
          <!-- <a class="dropdown-item" href="{% url 'flagstone:shuttle_list' %}">Shuttles</a>   -->
              
                 
        </div>
      </li>


    <!--   <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shuttles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          
          
          
        </div>
      </li>
 -->

<!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CARF
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'flagstone:praasa_create' %} ">New PRAASA</a> 
          <a class="dropdown-item" href="{% url 'flagstone:carf_list' %}">CARF List</a> 
          
          <a class="dropdown-item" href="#"></a> -->




      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Customers
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'flagstone:customer_list' %} ">Customers</a>
          <a class="dropdown-item" href="{% url 'flagstone:create_customer' %} ">New Customer</a>
          
          <a class="dropdown-item" href="#"></a>
          
           
        <!-- </div> -->
      <!-- </li> -->
      <!-- <li class="nav-item dropdown"> -->
        <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
          <!-- Vans -->
        <!-- </a> -->
        <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> -->
         <!--  <a class="dropdown-item"  href="{% url 'flagstone:van_list' %} ">Vans</a> -->
          <!-- <a class="dropdown-item" href="{% url 'flagstone:vaninspectionlog_list' %} ">Van Inspection Logs</a> -->
          <!-- <a class="dropdown-item" href="{% url 'flagstone:vanmaintenancelog_list' %} ">Van Maintenance Logs</a> -->
          <!-- <a class="dropdown-item" href="#"></a>           -->
        <!-- </div> -->
      <!-- </li> -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">          
        Drivers/Vans/Login</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
           <!-- <a class="dropdown-item"  href="{% url 'flagstone:van_list' %} ">Vans</a> -->
          <a class="dropdown-item" href="{% url 'flagstone:adobedriver_list' %} ">Drivers</a>
          <!-- <a class="dropdown-item" href="{% url 'flagstone:driverassignment_list' %} ">Driving Assignments</a> -->
          <!-- <a class="dropdown-item" href="{% url 'flagstone:timesheet_list' %} ">Driver Time Sheets</a> -->
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
           <!-- <a class="dropdown-item"  href="#">Register</a> -->
            {% if user.is_authenticated %}
           <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
           {% else %}
           <a class="dropdown-item" href="{% url 'login' %}">Login</a>
           {% endif %}
        </div>
      </li>
    </ul>
  </div>
</nav>

  {% if user.is_authenticated %}
    {% block body_content %}
    {% endblock %}
  {% else %}
    {% block login_content %}
      <div class="container">
        <div class="jumbotron">
          <a href="{% url 'login' %}"><b>LOGIN HERE</b></a></h2>
        </div>
      </div>
    {% endblock %}
  {% endif %}
<script src="{% static 'scripts/main.js' %}"></script>
</body>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

flagstone/templates/flagstone/customercarf_list.html
{% extends 'flagstone/base.html' %}
{% load static %}


{% block body_content %}

<div class="jumbotron">
	<table>
		<tr>
			<td class="text-left">
                <h1 class="text-info">Today is {% now "F jS, Y" %}</h1>
                <p><h1>Adobe Transportation</h1></p>

                <p><h2 class="text-primary">CARF MARCH 2020 MARRIOTT Shuttle Reservation List</h2></p>
            </td>            
            <td class="text-center"> </td>
			<td class="text-right">





            </td>
		</tr>
       
        <tr>
        <table>
            <address>
                <form method="GET" class="text-right">
                    <!-- {{ filter.form }} -->
                    <!-- <p><button type="submit" class="btn btn-primary">Search</button> </p></form> -->
            </address>
        </table>               
        </tr>
	</table>
  <h1></h1>
  
</div>
<div class="container">
    <table class="table table-condensed">
    <thead>
            

       

    </thead>
        <tbody>

            <!-- <th> -->
               <!--  <td class="text-left">
                    <strong>March 4th Arrivals</strong>

                {% for person in filter.qs %}
                {% if person.status_box == 'Active' and person.arrival_date.day == 4  %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}">{{person.name}} - {{person.arrival_flight}} - {{person.arrival_time}} {% endif %} </a></p>
            

                {% endfor %}
                </td> -->
                
            <!-- </th> -->
            <th>
                <td class="text-left">
                    <strong>March 20th Arrivals</strong><br><br>
                {% for person in carf_list %}

                {% if person.arrival_date.day == 20 and person.reservation_type != 'One Way Departure' and person.reservation_status == 'Reserved' %}          
                <p><a href="{% url 'flagstone:carf_statement' pk=person.pk %}">{{person.name}} - {{person.arrival_flight}} - {{person.arrival_time}}
               </a></p>
            
               {% endif %}
                {% endfor %}
                </td>

                
            </th>

            <th>
                <td class="text-left">
                    <strong>Arrived</strong><br><br>

                {% for person in carf_list %}

                {% if person.arrival_date.day == 20 and person.reservation_type != 'One Way Departure' and person.reservation_status != 'Reserved' %}          
                <p><a href="{% url 'flagstone:carf_statement' pk=person.pk %}"><span class="text-danger">{{person.name}} - {{person.departure_date}} - {{person.pickup_time}}</span>
               </a></p>
            
               {% endif %}
                {% endfor %}
                </td>
               
                
            </th>

            

        </tbody>
    </table>

</div>


{% endblock %}


    				

flagstone/templates/flagstone/driverassignment_list.html
{% extends 'flagstone/base.html' %}

{% block body_content %}

<div class="jumbotron">
  <h1><b>Adobe Transportation</b></h1>
  <h2 class="text-primary">Driver Assignment  List</h2>
</div>


  <div class="container">
    {% for info in driverassignment_list %}
	<p><a href="{{info.id}}">{{ info.pudo }}, {{ info.driver }}</a></p>
    {% endfor %}
  </div>

{% endblock %}


driver
van
pudo
ap_pudo
sp_serv
sp_evnt

{% if info.pudo != 'None' %}
      <p><a href="{{info.id}}">{{ info.pudo }}, {{ info.first_name }}</a></p>
    {% elif info.ap_pudo != 'None' %}
    <p><a href="{{info.id}}">{{ info.pudo }}, {{ info.first_name }}</a></p>
{% endif %}

flagstone/templates/flagstone/praasa_march2020_listAAA.html
{% extends 'flagstone/base.html' %}
{% load static %}


{% block body_content %}

<div class="jumbotron">
	<table>
		<tr>
			<td class="text-left"><h1>Adobe Transportation</h1><p><h2 class="text-primary">PRAASA MARCH 2020</h2></p></td>            
            <td class="text-center"></td>
			<td class="text-right">

            </td>
		</tr>
       
        <tr>
        <table>
            <address>
                <form method="GET" class="text-right">
                    {{ filter.form }}
                    <p><button type="submit" class="btn btn-primary">Search</button> </p></form>
            </address>
        </table>               
        </tr>
	</table>
  <h1></h1>
  
</div>
<div class="container">
    <table class="table table-condensed">
    <thead>
            

       

    </thead>
        <tbody>

            <th>
               <!--  <td class="text-left">
                    <strong>March 4th Arrivals</strong>

                {% for person in filter.qs %}
                {% if person.status_box == 'Active' and person.arrival_date.day == 4  %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}">{{person.name}} - {{person.arrival_flight}} - {{person.arrival_time}} {% endif %} </a></p>
            

                {% endfor %}
                </td> -->
                
            </th>
            <th>
                <td class="text-left">
                    <strong>March 5th Arrivals</strong>

                {% for person in filter.qs %}

                {% if person.arrival_date.day == 5 and person.status_box == 'Active' %}
                          
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}">{{person.name}} - {{person.arrival_flight}} - {{person.arrival_time}}
                {% endif %} </a></p>
            

                {% endfor %}
                </td>

                
            </th>

            <th>
                <td class="text-left">
                    <strong>Arrived</strong>

                {% for person in filter.qs %}

                {% if person.arrival_date.day == 5 and person.status_box == 'Arrived'  %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}"><span class="text-danger">{{person.name}} - {{person.arrival_flight}} - {{person.departure_date}}-{{person.pickup_time}}{% endif %} </span></a></p>
            

                {% endfor %}
               <!--  </td>


                <td class="text-left">
                    <strong>March 7th Departures</strong>

                {% for person in filter.qs %}

                {% if person.departure_date.day == 7 %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}"><strong class="text-danger">{{person.name}} - {{person.departure_date}} - {{person.departure_time}}{% endif %} </a></p></strong>
            

                {% endfor %}
                </td> -->

                <!-- <td class="text-left">
                    <strong>March 8th Departures</strong>

                {% for person in filter.qs %}

                {% if person.departure_date.day == 8 %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}"><strong class="text-danger">{{person.name}} - {{person.departure_date}} - {{person.departure_time}}{% endif %} </a></p></strong>
            

                {% endfor %}
                </td> -->

                <!-- <td class="text-left">
                    <strong>March 9th Departures</strong>

                {% for person in filter.qs %}

                {% if person.departure_date.day == 9 %}               
                <p><a href="{% url 'flagstone:praasa_statement' pk=person.pk %}"><strong class="text-danger">{{person.name}} - {{person.departure_date}} - {{person.departure_time}}{% endif %} </a></p></strong>
            

                {% endfor %}
                </td> -->
                
            </th>

        </tbody>
    </table>

</div>


{% endblock %}


    				

flagstone/templates/flagstone/van_detail.html
{% extends 'flagstone/base.html' %}


{% block body_content %}
<div class="jumbotron"><h1><b>Adobe Transportation</b></h1><h2>Van Details</h2></div>
<div class="container">

	
<h4><b>{{van_detail.van_num}}</b> - Van Number </h4><br>
<h4><b>{{van_detail.vin}}</b> - VIN</h4><br>
<h4><b>{{van_detail.year_make_model}}</b> - Year/Make/Model</h4><br>
<h4><b>{{van_detail.plate}}</b> - License Plate </h4><br>
<h4><b>{{van_detail.tag_exp}}</b> - Tags Exp Date </h4><br>







</div>
<br>
<div class="container">
	<p><a class="btn btn-danger" href="{% url 'flagstone:update_van' pk=van_detail.pk %}">UPDATE</a></p>
</div>



{% endblock %}

flagstone/templates/flagstone/van_list.html
{% extends 'flagstone/base.html' %}

{% block body_content %}

<div class="jumbotron">
  <h1><b>Adobe Transportation</b></h1>
  <h2 class="text-primary">Van List</h2>
</div>


  <div class="container">
    {% for van in van_list %}
      <p><a href="{{van.id}}">{{ van.van_num}}, {{ van.plate }}</a></p>
    {% endfor %}
  </div>

{% endblock %}